-- Drop the duplicate foreign key constraint that was manually added at some point
-- This allows PostgREST to unambiguously resolve the `groups` <-> `group_members` join implicitly.

ALTER TABLE public.group_members
DROP CONSTRAINT IF EXISTS fk_group_members_group;

-- Ensure the primary constraint remains intact (the one auto-generated by supabase studio usually)
-- If for some reason fk_group_members_group was the only one (which it isn't based on the PGRST201 error), 
-- the error explicitly confirmed group_members_group_id_fkey ALSO exists.
